import { ActivitiesDirectory } from "./ActivitiesDirectory";
import type { ActivityDescription } from "../types/Form";

export class Activity {

    id: string = crypto.randomUUID()

    theme: string = ""
    format: string = ""
    name: string = ""
    proceedings: string = ""
    timing: string = ""
    goals: string = ""
    tools: string[] = []
    evalCriterions: string = ""
    results: string = ""

    // Allows a **semi-verification** that a given ID
    // was generated by the built-in function 'crypto.randomUUID()'
    // See https://w3c.github.io/webcrypto/#Crypto-method-randomUUID for more information
    private static UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

    static verifyID(id: string): boolean {
        return this.UUID_REGEX.test(id)
    }

    static getActivity(data: ActivityDescription): Activity {
        const activity = new Activity()
        // It the activity description 'data' has already
        // a valid ID, does not change it
        activity.id = this.verifyID(data.id) ? data.id : activity.id 
        activity.theme = data.theme
        activity.format = data.format
        activity.name = data.name
        activity.proceedings = data.proceedings
        activity.timing = data.timing
        activity.goals = data.goals
        activity.tools = data.tools
        activity.evalCriterions = data.evalCriterions
        activity.results = data.results

        return activity
    }

    static getDescription(activity: Activity): ActivityDescription {

        const data: ActivityDescription = {
            id: activity.id,
            theme: activity.theme,
            format: activity.format,
            name: activity.name,
            proceedings: activity.proceedings,
            timing: activity.timing,
            goals: activity.goals,
            tools: activity.tools,
            evalCriterions: activity.evalCriterions,
            results: activity.results
        }

        return data
    }

    static saveFromDescription(data: ActivityDescription): Activity {
        const activity: Activity = this.getActivity(data)
        ActivitiesDirectory.addActivity(activity)
        return activity
    }

}