import type { Activity } from "./Activity";
import { GeneralInfo } from "./GeneralInfo";
import { RemindersNGoals } from "./RemindersNGoals";
import { SessionDebriefing } from "./SessionDebriefing";
import { SessionsDirectory } from "./SessionsDirectory";
import { ActivitiesDirectory } from "./ActivitiesDirectory";
import type { ActivitySummary, SessionDescription } from "../types/Form";

export class Session {

  id: string = crypto.randomUUID()

  generalInfo: GeneralInfo = new GeneralInfo();
  remindersNGoals: RemindersNGoals = new RemindersNGoals();
  activities: string[] = [];
  debriefing: SessionDebriefing = new SessionDebriefing();

  // Allows a **semi-verification** that a given ID
  // was generated by the built-in function 'crypto.randomUUID()'
  // See https://w3c.github.io/webcrypto/#Crypto-method-randomUUID for more information
  private static UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

  static verifyID(id: string): boolean {
    return this.UUID_REGEX.test(id)
  }

  static getSession(data: SessionDescription): Session {
    const session: Session = new Session()
    // It the session description 'data' has already
    // a valid ID, does not change it
    session.id = this.verifyID(data.id) ? data.id : session.id
    session.generalInfo = data.generalInfo
    session.remindersNGoals = data.remindersNGoals
    session.activities = data.activities.map((activity) => activity.id)

    return session
  }

  static getDescription(session: Session): SessionDescription {

    const data: SessionDescription = {
      id: session.id,

      generalInfo: {
        theme: session.generalInfo.theme,
        tutorsName: session.generalInfo.tutorsName,
        tutoredNumber: session.generalInfo.tutoredNumber,
        date: session.generalInfo.date
      },

      remindersNGoals: {
        remindersFromLastSess: session.remindersNGoals.remindersFromLastSess,
        pedagogicalGoals: session.remindersNGoals.pedagogicalGoals,
        keyMessages: session.remindersNGoals.keyMessages
      },

      // Transforms Activity[] into ActivitySummary[]
      activities: session.activities.map((id) => {
        const activity: Activity | null = ActivitiesDirectory.getActivityByID(id)
        const summary: ActivitySummary | null = activity !== null ? {
          id: id,
          theme: activity.theme,
          name: activity.name
        } : null

        return summary !== null ? summary : {id: "", theme: "", name: ""}
      })
    }

    return data
  }

  static saveFromDescription(data: SessionDescription): Session {
    const session: Session = this.getSession(data)
    SessionsDirectory.addSession(session)

    return session
  }

}